-- ============================================================
-- Nurturing Healthy Kids - Database Schema
-- ============================================================

-- 0. Drop Existing Tables
-- Order matters: junction tables (which reference
-- other tables) are dropped before the tables they reference, and
-- CASCADE REMOVES any leftover foreign key dependencies.

DROP TABLE IF EXISTS 
    activity_variety_tag,
    activity_location_category,
    activity,
    open_space,
    variety_tag,
    weather_dependency,
    mission_type,
    supervision_level,
    equipment_required_tag,
    indoor_outdoor_tag,
    location_category,
    postcode
CASCADE;

-- 1. Lookup Tables

CREATE TABLE POSTCODE (
    postcode VARCHAR(10) PRIMARY KEY,
    latitude DECIMAL(9, 6) NOT NULL,
    longitude DECIMAL(9, 6) NOT NULL,
    suburbs TEXT
);
-- One row per postcode, used to turn a user's typed
-- postcode into a location.
 
CREATE TABLE LOCATION_CATEGORY (
    category_name VARCHAR(50) PRIMARY KEY
);
INSERT INTO LOCATION_CATEGORY (category_name) VALUES 
('playground'), ('wetland'), ('bushland'), ('nature'), ('park'), ('trail'), ('active_sport'), ('home');
-- The 8 kinds of open space a location can be.
 
CREATE TABLE INDOOR_OUTDOOR_TAG (
    tag_name VARCHAR(50) PRIMARY KEY
);
INSERT INTO INDOOR_OUTDOOR_TAG (tag_name) VALUES ('Indoor'), ('Outdoor'), ('Either');
-- Where an activity takes place.
 
CREATE TABLE EQUIPMENT_REQUIRED_TAG (
    tag_name VARCHAR(100) PRIMARY KEY
);
INSERT INTO EQUIPMENT_REQUIRED_TAG (tag_name) VALUES 
('None'), ('Household Items'), ('Basic Sports Equipment'), ('Specialised Equipment');
-- Broad category of equipment an activity needs, for filtering.
 
CREATE TABLE SUPERVISION_LEVEL (
    level_name VARCHAR(50) PRIMARY KEY
);
INSERT INTO SUPERVISION_LEVEL (level_name) VALUES ('Independent-Play-Safe'), ('Needs Supervision');
-- Whether an adult needs to be present.
 
CREATE TABLE MISSION_TYPE (
    type_name VARCHAR(50) PRIMARY KEY
);
INSERT INTO MISSION_TYPE (type_name) VALUES ('Location-Based'), ('Home-Based'), ('Location-Agnostic');
-- Whether an activity needs an open space, needs home/yard, or works anywhere.
 
CREATE TABLE WEATHER_DEPENDENCY (
    dependency_name VARCHAR(50) PRIMARY KEY
);
INSERT INTO WEATHER_DEPENDENCY (dependency_name) VALUES 
('Weather-Independent'), ('Outdoor-Fair-Weather-Only'), ('Indoor-Fallback-Available');
-- How sensitive an activity is to weather conditions.
 
CREATE TABLE VARIETY_TAG (
    tag_name VARCHAR(50) PRIMARY KEY
);
INSERT INTO VARIETY_TAG (tag_name) VALUES 
('Energised Activity'), ('Coordination'), ('Imaginative Play'), ('Creative'), 
('Construction'), ('Nature'), ('Exploration'), ('Teamwork'), ('Social'), 
('Quiet'), ('Water Play'), ('Throwing & Catching'), ('Solo'), ('Pairs'), ('Group/Family');
-- Descriptive play-style tags. An activity can have more than one.
 
 
-- 2. Core Entities
-- The two main things the app works with: real places, and activities.
 
CREATE TABLE OPEN_SPACE (
    open_space_id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    latitude DECIMAL(9, 6) NOT NULL,
    longitude DECIMAL(9, 6) NOT NULL,
    category VARCHAR(50) NOT NULL,
    CONSTRAINT fk_open_space_category FOREIGN KEY (category) REFERENCES LOCATION_CATEGORY(category_name) ON UPDATE CASCADE ON DELETE RESTRICT
);
-- A real, physical place a family can go to (park, trail, oval, etc).
-- open_space_id keeps the government's own stable ID, so it's just
-- loaded in directly rather than generated by the database.
 
CREATE TABLE ACTIVITY (
    mission_id VARCHAR(50) PRIMARY KEY,
    activity_title VARCHAR(255) NOT NULL,
    description TEXT,
    equipment_needed TEXT,
    instruction_text TEXT,
    duration_minutes INT,
    age_5_7 CHAR(1) DEFAULT 'N' CHECK (age_5_7 IN ('Y', 'N')),
    age_8_9 CHAR(1) DEFAULT 'N' CHECK (age_8_9 IN ('Y', 'N')),
    age_10_12 CHAR(1) DEFAULT 'N' CHECK (age_10_12 IN ('Y', 'N')),
    
    indoor_outdoor_tag VARCHAR(50) NULL,
    equipment_required_tag VARCHAR(100) NULL,
    supervision_level VARCHAR(50) NULL,
    mission_type VARCHAR(50) NULL,
    weather_dependency VARCHAR(50) NULL,
    
    CONSTRAINT fk_act_indoor_outdoor FOREIGN KEY (indoor_outdoor_tag) REFERENCES INDOOR_OUTDOOR_TAG(tag_name) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_act_equipment FOREIGN KEY (equipment_required_tag) REFERENCES EQUIPMENT_REQUIRED_TAG(tag_name) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_act_supervision FOREIGN KEY (supervision_level) REFERENCES SUPERVISION_LEVEL(level_name) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_act_mission_type FOREIGN KEY (mission_type) REFERENCES MISSION_TYPE(type_name) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_act_weather FOREIGN KEY (weather_dependency) REFERENCES WEATHER_DEPENDENCY(dependency_name) ON UPDATE CASCADE ON DELETE SET NULL
);
-- One row per activity variant (e.g. a 30-min and a 45-min version
-- of the same activity are two separate rows). Each activity is
-- tagged with the lookup values above; tags are optional (NULL
-- allowed) since not every activity fits every dimension.
 
 
-- 3. Junction Tables
-- Link activities to the location categories and variety tags they
-- support. A single activity can have several of each.
 
CREATE TABLE ACTIVITY_LOCATION_CATEGORY (
    mission_id VARCHAR(50) NOT NULL,
    category_name VARCHAR(50) NOT NULL,
    open_space_ref_id INT NULL,
    PRIMARY KEY (mission_id, category_name),
    CONSTRAINT fk_alc_mission FOREIGN KEY (mission_id) REFERENCES ACTIVITY(mission_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_alc_category FOREIGN KEY (category_name) REFERENCES LOCATION_CATEGORY(category_name) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_alc_open_space FOREIGN KEY (open_space_ref_id) REFERENCES OPEN_SPACE(open_space_id) ON UPDATE CASCADE ON DELETE SET NULL
);
-- Which location categories (e.g. "park", "playground") an activity
-- works at. open_space_ref_id can optionally pin an activity to one
-- specific real place, instead of just a category.
 
CREATE TABLE ACTIVITY_VARIETY_TAG (
    mission_id VARCHAR(50) NOT NULL,
    tag_name VARCHAR(50) NOT NULL,
    PRIMARY KEY (mission_id, tag_name),
    CONSTRAINT fk_avt_mission FOREIGN KEY (mission_id) REFERENCES ACTIVITY(mission_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_avt_tag FOREIGN KEY (tag_name) REFERENCES VARIETY_TAG(tag_name) ON UPDATE CASCADE ON DELETE CASCADE
);
-- Which variety tags (e.g. "Nature", "Teamwork") apply to an activity.