-- ============================================================
-- Nurturing Healthy Kids - Seed Data
-- ============================================================

BEGIN;

-- 1. POSTCODE
\copy postcode (postcode, latitude, longitude, suburbs) FROM '/csvdata/postcode_location_db.csv' WITH (FORMAT csv, HEADER true, NULL '')
 
 
-- 2. OPEN_SPACE
\copy open_space (open_space_id, name, latitude, longitude, category) FROM '/csvdata/open_space_location_db.csv' WITH (FORMAT csv, HEADER true, NULL '')
 
 
-- 3. ACTIVITY + ACTIVITY_VARIETY_TAG
-- activities_db.csv has one extra column (variety_tags, e.g. "Nature|Exploration")
-- that isn't a column on activity, it's the activity_variety_tag
-- junction table. A staging table holds the raw row so it can be split:
-- one insert goes to activity (without variety_tags), a second insert
-- splits variety_tags on "|" into one row per tag.
CREATE TEMP TABLE staging_activity (
    mission_id              VARCHAR(50),
    activity_title          VARCHAR(255),
    description             TEXT,
    equipment_needed        TEXT,
    instruction_text        TEXT,
    indoor_outdoor_tag      VARCHAR(50),
    duration_minutes        INT,
    age_5_7                 CHAR(1),
    age_8_9                 CHAR(1),
    age_10_12               CHAR(1),
    equipment_required_tag  VARCHAR(100),
    supervision_level       VARCHAR(50),
    mission_type            VARCHAR(50),
    weather_dependency      VARCHAR(50),
    variety_tags            TEXT,
    social_tag              VARCHAR(50)
);
\copy staging_activity FROM '/csvdata/activities_db.csv' WITH (FORMAT csv, HEADER true, NULL '')
 
INSERT INTO activity (
    mission_id, activity_title, description, equipment_needed, instruction_text,
    duration_minutes, age_5_7, age_8_9, age_10_12,
    indoor_outdoor_tag, equipment_required_tag, supervision_level, mission_type, weather_dependency,
    social_tag
)
SELECT
    mission_id, activity_title, description, equipment_needed, instruction_text,
    duration_minutes, age_5_7, age_8_9, age_10_12,
    indoor_outdoor_tag, equipment_required_tag, supervision_level, mission_type, weather_dependency,
    social_tag
FROM staging_activity;

-- Icon mappings are kept in the database seed so the CSV is not required at runtime.
UPDATE activity AS a
SET icon_file = mapping.icon_file
FROM (VALUES
    ('MIS-001', 'nature-scavenger-hunt.svg'),
    ('MIS-002', 'nature-scavenger-hunt.svg'),
    ('MIS-003', 'mini-hike.svg'),
    ('MIS-004', 'mini-hike.svg'),
    ('MIS-005', 'kite-flying-session.svg'),
    ('MIS-006', 'bike-and-scooter-skills-circuit.svg'),
    ('MIS-007', 'frisbee-throwing-challenge.svg'),
    ('MIS-008', 'frisbee-throwing-challenge.svg'),
    ('MIS-009', 'bird-watching-walk.svg'),
    ('MIS-010', 'fitness-trail-circuit.svg'),
    ('MIS-011', 'team-tag-game.svg'),
    ('MIS-012', 'nature-art-collage.svg'),
    ('MIS-013', 'nature-art-collage.svg'),
    ('MIS-014', 'photo-scavenger-hunt.svg'),
    ('MIS-015', 'ball-skills-practice.svg'),
    ('MIS-016', 'ball-skills-practice.svg'),
    ('MIS-017', 'shadow-tracing-game.svg'),
    ('MIS-018', 'cloud-storytelling.svg'),
    ('MIS-019', 'cloud-storytelling.svg'),
    ('MIS-020', 'mini-orienteering-challenge.svg'),
    ('MIS-021', 'grass-tumbling-races.svg'),
    ('MIS-022', 'exploration-walk.svg'),
    ('MIS-023', 'skipping-rope-relay.svg'),
    ('MIS-024', 'target-kicking-practice.svg'),
    ('MIS-025', 'backyard-obstacle-course.svg'),
    ('MIS-026', 'backyard-obstacle-course.svg'),
    ('MIS-027', 'pillow-fort-building.svg'),
    ('MIS-028', 'pillow-fort-building.svg'),
    ('MIS-029', 'kitchen-fizzy-science-experiment.svg'),
    ('MIS-030', 'backyard-water-balloon-toss.svg'),
    ('MIS-031', 'backyard-water-balloon-toss.svg'),
    ('MIS-032', 'cardboard-box-car-building.svg'),
    ('MIS-033', 'cardboard-box-car-building.svg'),
    ('MIS-034', 'treasure-hunt.svg'),
    ('MIS-035', 'treasure-hunt.svg'),
    ('MIS-036', 'backyard-bird-feeder-craft.svg'),
    ('MIS-037', 'sock-puppet-show-performance.svg'),
    ('MIS-038', 'balloon-volleyball.svg'),
    ('MIS-039', 'driveway-chalk-art-mural.svg'),
    ('MIS-040', 'driveway-chalk-art-mural.svg'),
    ('MIS-041', 'mini-chef-cooking-challenge.svg'),
    ('MIS-042', 'laundry-basket-basketball.svg'),
    ('MIS-043', 'freeze-dance-music-challenge.svg'),
    ('MIS-044', 'freeze-dance-music-challenge.svg'),
    ('MIS-045', 'family-charades-guessing-game.svg'),
    ('MIS-046', 'story-chain-building-game.svg'),
    ('MIS-047', 'story-chain-building-game.svg'),
    ('MIS-048', 'simon-says-fitness-challenge.svg'),
    ('MIS-049', 'simon-says-fitness-challenge.svg'),
    ('MIS-050', 'twenty-questions-guessing-game.svg'),
    ('MIS-051', 'fitness-bootcamp-circuit.svg'),
    ('MIS-052', 'fitness-bootcamp-circuit.svg'),
    ('MIS-053', 'obstacle-relay.svg'),
    ('MIS-054', 'bench-balance-beam-challenge.svg'),
    ('MIS-055', 'bug-hunting-expedition.svg'),
    ('MIS-056', 'bug-hunting-expedition.svg'),
    ('MIS-057', 'cricket-skills-practice.svg'),
    ('MIS-058', 'rock-skimming-challenge.svg'),
    ('MIS-059', 'sack-race-challenge.svg'),
    ('MIS-060', 'tree-climbing-safety-challenge.svg'),
    ('MIS-061', 'geocaching-treasure-hunt.svg'),
    ('MIS-062', 'geocaching-treasure-hunt.svg'),
    ('MIS-063', 'kite-string-relay.svg'),
    ('MIS-064', 'bench-yoga-pose-challenge.svg'),
    ('MIS-065', 'vegetable-id-walk.svg'),
    ('MIS-066', 'stargazing-night-walk.svg'),
    ('MIS-067', 'stargazing-night-walk.svg'),
    ('MIS-068', 'obstacle-hopscotch-trail.svg'),
    ('MIS-069', 'sprint-and-skip-relay.svg'),
    ('MIS-070', 'leaf-rubbing-nature-journal.svg'),
    ('MIS-071', 'leaf-rubbing-nature-journal.svg'),
    ('MIS-072', 'wildlife-sound-listening-walk.svg'),
    ('MIS-073', 'team-building-challenge.svg'),
    ('MIS-074', 'team-building-challenge.svg'),
    ('MIS-075', 'balloon-rocket-launch.svg'),
    ('MIS-076', 'tug-of-war-challenge.svg'),
    ('MIS-077', 'backyard-mini-golf-course-building.svg'),
    ('MIS-078', 'backyard-mini-golf-course-building.svg'),
    ('MIS-079', 'family-board-game-tournament.svg'),
    ('MIS-080', 'backyard-camping-adventure.svg'),
    ('MIS-081', 'backyard-camping-adventure.svg'),
    ('MIS-082', 'kitchen-bench-baking-project.svg'),
    ('MIS-083', 'dance-routine-choreography.svg'),
    ('MIS-084', 'backyard-giant-bubble-blowing-challenge.svg'),
    ('MIS-085', 'backyard-giant-bubble-blowing-challenge.svg'),
    ('MIS-086', 'recycled-robot-building.svg'),
    ('MIS-087', 'recycled-robot-building.svg'),
    ('MIS-088', 'backyard-herb-garden-planting.svg'),
    ('MIS-089', 'backyard-herb-garden-planting.svg'),
    ('MIS-090', 'blanket-fort-story-night.svg'),
    ('MIS-091', 'backyard-chalk-hopscotch-course.svg'),
    ('MIS-092', 'backyard-chalk-hopscotch-course.svg'),
    ('MIS-093', 'family-trivia-quiz-night.svg'),
    ('MIS-094', 'family-trivia-quiz-night.svg'),
    ('MIS-095', 'memory-card-matching-game.svg'),
    ('MIS-096', 'would-you-rather-question-game.svg'),
    ('MIS-097', 'would-you-rather-question-game.svg'),
    ('MIS-098', 'musical-statues-dance-game.svg'),
    ('MIS-099', 'family-drawing-telephone-game.svg'),
    ('MIS-100', 'family-drawing-telephone-game.svg'),
    ('MIS-101', 'sandpit-castle-building-challenge.svg'),
    ('MIS-102', 'sandpit-castle-building-challenge.svg'),
    ('MIS-103', 'fossil-and-rock-hunting-walk.svg'),
    ('MIS-104', 'relay-baton-race.svg'),
    ('MIS-105', 'relay-baton-race.svg'),
    ('MIS-106', 'balance-bike-course.svg'),
    ('MIS-107', 'soccer-skills-clinic.svg'),
    ('MIS-108', 'nature-colour-hunt.svg'),
    ('MIS-109', 'bushland-sensory-walk.svg'),
    ('MIS-110', 'bushland-sensory-walk.svg'),
    ('MIS-111', 'long-jump-challenge.svg'),
    ('MIS-112', 'picnic-rug-story-circle.svg'),
    ('MIS-113', 'balance-and-wobble-challenge.svg'),
    ('MIS-114', 'balance-and-wobble-challenge.svg'),
    ('MIS-115', 'puddle-jumping-adventure.svg'),
    ('MIS-116', 'grass-maze-navigation-game.svg'),
    ('MIS-117', 'distance-throwing-challenge.svg'),
    ('MIS-118', 'distance-throwing-challenge.svg'),
    ('MIS-119', 'tree-bark-rubbing-nature-craft.svg'),
    ('MIS-120', 'nature-sound-mapping-walk.svg'),
    ('MIS-121', 'follow-the-leader-fitness-trail.svg'),
    ('MIS-122', 'follow-the-leader-fitness-trail.svg'),
    ('MIS-123', 'kite-decorating-and-flying-day.svg'),
    ('MIS-124', 'four-square-ball-game.svg'),
    ('MIS-125', 'four-square-ball-game.svg'),
    ('MIS-126', 'backyard-fairy-garden-building.svg'),
    ('MIS-127', 'backyard-fairy-garden-building.svg'),
    ('MIS-128', 'shadow-puppet-theatre.svg'),
    ('MIS-129', 'backyard-rain-gauge-science-project.svg'),
    ('MIS-130', 'backyard-rain-gauge-science-project.svg'),
    ('MIS-131', 'paper-plane-design-lab.svg'),
    ('MIS-132', 'backyard-warrior-training-course.svg'),
    ('MIS-133', 'backyard-warrior-training-course.svg'),
    ('MIS-134', 'sensory-bin-exploration.svg'),
    ('MIS-135', 'backyard-vegetable-patch-harvest-helper.svg'),
    ('MIS-136', 'backyard-vegetable-patch-harvest-helper.svg'),
    ('MIS-137', 'diy-board-game-design.svg'),
    ('MIS-138', 'backyard-water-relay-race.svg'),
    ('MIS-139', 'backyard-water-relay-race.svg'),
    ('MIS-142', 'family-cooking-show.svg'),
    ('MIS-143', 'family-cooking-show.svg'),
    ('MIS-144', 'family-rhyme-time-challenge.svg'),
    ('MIS-145', 'family-rhyme-time-challenge.svg'),
    ('MIS-146', 'categories-word-game.svg'),
    ('MIS-147', 'balloon-pop-trivia-game.svg'),
    ('MIS-148', 'silent-ball-passing-game.svg'),
    ('MIS-149', 'silent-ball-passing-game.svg'),
    ('MIS-150', 'family-riddle-relay.svg'),
    ('MIS-151', 'hula-hoop-trick-circuit.svg'),
    ('MIS-152', 'hula-hoop-trick-circuit.svg'),
    ('MIS-153', 'egg-and-spoon-relay-race.svg'),
    ('MIS-154', 'egg-and-spoon-relay-race.svg'),
    ('MIS-155', 'animal-track-spotting-walk.svg'),
    ('MIS-156', 'musical-chairs-challenge.svg'),
    ('MIS-157', 'netball-shooting-practice.svg'),
    ('MIS-158', 'netball-shooting-practice.svg'),
    ('MIS-159', 'fallen-log-balance-and-nature-gym-circuit.svg'),
    ('MIS-160', 'sprint-timing-challenge.svg'),
    ('MIS-161', 'land-art-sculpture-building.svg'),
    ('MIS-162', 'frisbee-golf-circuit.svg'),
    ('MIS-163', 'frisbee-golf-circuit.svg'),
    ('MIS-164', 'basketball-shooting-skills-challenge.svg'),
    ('MIS-165', 'weather-observation-and-cloud-journal-walk.svg'),
    ('MIS-166', 'capture-the-flag-team-game.svg'),
    ('MIS-167', 'capture-the-flag-team-game.svg'),
    ('MIS-168', 'nature-scent-blind-walk.svg'),
    ('MIS-169', 'beanbag-ladder-toss-challenge.svg'),
    ('MIS-170', 'community-tree-planting-helper.svg'),
    ('MIS-171', 'community-tree-planting-helper.svg'),
    ('MIS-172', 'giant-stacking-tower-challenge.svg'),
    ('MIS-173', 'native-plant-identification-walk.svg'),
    ('MIS-174', 'native-plant-identification-walk.svg'),
    ('MIS-175', 'handball-wall-skills-practice.svg'),
    ('MIS-176', 'backyard-bird-nest-box-building.svg'),
    ('MIS-177', 'backyard-bird-nest-box-building.svg'),
    ('MIS-178', 'marble-run-construction-challenge.svg'),
    ('MIS-179', 'backyard-insect-hotel-building.svg'),
    ('MIS-180', 'backyard-insect-hotel-building.svg'),
    ('MIS-181', 'sock-matching-speed-sort-game.svg'),
    ('MIS-182', 'newspaper-fashion-design-challenge.svg'),
    ('MIS-185', 'egg-drop-engineering-challenge.svg'),
    ('MIS-186', 'backyard-weather-vane-building-project.svg'),
    ('MIS-187', 'family-karaoke-talent-show.svg'),
    ('MIS-188', 'family-karaoke-talent-show.svg'),
    ('MIS-189', 'backyard-time-capsule-creation.svg'),
    ('MIS-190', 'family-card-tower-building-challenge.svg'),
    ('MIS-191', 'family-card-tower-building-challenge.svg'),
    ('MIS-192', 'backyard-solar-oven-treat-experiment.svg'),
    ('MIS-193', 'backyard-solar-oven-treat-experiment.svg'),
    ('MIS-194', 'family-two-truths-and-a-tale-game.svg'),
    ('MIS-195', 'family-two-truths-and-a-tale-game.svg'),
    ('MIS-196', 'alphabet-a-z-object-hunt-game.svg'),
    ('MIS-197', 'family-human-knot-puzzle-game.svg'),
    ('MIS-198', 'copy-cat-sound-mimicry-game.svg'),
    ('MIS-199', 'copy-cat-sound-mimicry-game.svg'),
    ('MIS-200', 'family-compliment-circle-game.svg'),
    ('MIS-201', 'i-spy-colour-and-shape-game.svg'),
    ('MIS-202', 'i-spy-colour-and-shape-game.svg'),
    ('MIS-203', 'thumb-war-tournament.svg'),
    ('MIS-204', 'rock-paper-scissors-championship-ladder.svg'),
    ('MIS-205', 'rock-paper-scissors-championship-ladder.svg'),
    ('MIS-206', 'family-tongue-twister-challenge.svg'),
    ('MIS-207', 'staring-contest-showdown.svg'),
    ('MIS-208', 'times-tables-speed-quiz.svg'),
    ('MIS-209', 'times-tables-speed-quiz.svg'),
    ('MIS-210', 'family-impersonation-guessing-game.svg'),
    ('MIS-211', 'silliest-face-contest.svg'),
    ('MIS-212', 'silly-debate-time.svg'),
    ('MIS-213', 'silly-debate-time.svg'),
    ('MIS-214', 'guess-the-object-by-touch.svg'),
    ('MIS-215', 'memory-chain-shopping-list-game.svg'),
    ('MIS-216', 'memory-chain-shopping-list-game.svg'),
    ('MIS-217', 'hum-that-tune-guessing-game.svg'),
    ('MIS-218', 'mirror-movement-copy-game.svg'),
    ('MIS-219', 'mirror-movement-copy-game.svg'),
    ('MIS-220', 'family-show-and-tell-time.svg'),
    ('MIS-221', 'family-accent-challenge.svg'),
    ('MIS-222', 'family-balancing-statue-contest.svg'),
    ('MIS-223', 'family-balancing-statue-contest.svg'),
    ('MIS-224', 'one-minute-talking-challenge.svg'),
    ('MIS-225', 'opposite-day-challenge.svg'),
    ('MIS-226', 'guess-the-number-range-game.svg'),
    ('MIS-227', 'guess-the-number-range-game.svg'),
    ('MIS-228', 'pattern-clap-rhythm-game.svg'),
    ('MIS-229', 'hot-potato-category-word-game.svg'),
    ('MIS-230', 'hot-potato-category-word-game.svg'),
    ('MIS-231', 'balance-on-one-foot-endurance-challenge.svg'),
    ('MIS-232', 'family-slow-motion-race.svg'),
    ('MIS-233', 'guess-what-s-missing-memory-tray-game.svg'),
    ('MIS-234', 'guess-what-s-missing-memory-tray-game.svg'),
    ('MIS-235', 'family-gratitude-sharing-circle.svg'),
    ('MIS-236', 'word-association-chain-game.svg'),
    ('MIS-237', 'word-association-chain-game.svg'),
    ('MIS-238', 'higher-or-lower-estimation-game.svg'),
    ('MIS-239', 'would-you-survive-silly-scenario-game.svg'),
    ('MIS-240', 'would-you-survive-silly-scenario-game.svg'),
    ('MIS-241', 'balance-book-on-head-walking-challenge.svg'),
    ('MIS-242', 'blind-drawing-guessing-game.svg'),
    ('MIS-243', 'blind-drawing-guessing-game.svg'),
    ('MIS-244', 'tightrope-balance-line-walk.svg'),
    ('MIS-245', 'family-longest-word-challenge.svg'),
    ('MIS-246', 'guess-the-price-estimation-game.svg'),
    ('MIS-247', 'guess-the-price-estimation-game.svg'),
    ('MIS-248', 'family-never-have-i-ever-rounds.svg'),
    ('MIS-249', 'guess-the-continuing-pattern-game.svg'),
    ('MIS-250', 'guess-the-continuing-pattern-game.svg'),
    ('MIS-251', 'animal-walk-hallway-race.svg'),
    ('MIS-252', 'floor-is-lava-cushion-crossing.svg'),
    ('MIS-253', 'sock-ball-bowling.svg'),
    ('MIS-254', 'coin-flip-exercise-game.svg'),
    ('MIS-255', 'superhero-training-circuit.svg'),
    ('MIS-256', 'cup-stacking-speed-pyramid.svg'),
    ('MIS-257', 'paper-stepping-stones-river-crossing.svg'),
    ('MIS-258', 'balloon-waddle-race.svg'),
    ('MIS-259', 'indoor-rainbow-scavenger-dash.svg'),
    ('MIS-260', 'two-sock-juggling-practice.svg'),
    ('MIS-261', 'animal-yoga-stretch-break.svg'),
    ('MIS-262', 'tiptoe-ninja-sneak.svg'),
    ('MIS-263', 'wheelbarrow-walk-race.svg'),
    ('MIS-264', 'hide-the-teddy-hot-and-cold.svg'),
    ('MIS-265', 'backyard-fence-to-fence-sprint-trial.svg'),
    ('MIS-266', 'skipping-rope-one-minute-challenge.svg'),
    ('MIS-267', 'soccer-ball-juggling-record.svg'),
    ('MIS-268', 'backyard-mini-beast-count.svg'),
    ('MIS-269', 'watering-can-garden-round.svg'),
    ('MIS-270', 'clothes-peg-speed-clip.svg'),
    ('MIS-271', 'backyard-sit-spot-sound-count.svg'),
    ('MIS-272', 'sink-or-float-kitchen-test.svg'),
    ('MIS-273', 'window-watch-tally.svg'),
    ('MIS-274', 'draw-your-day-comic-strip.svg')
) AS mapping(mission_id, icon_file)
WHERE a.mission_id = mapping.mission_id;

INSERT INTO activity_variety_tag (mission_id, tag_name)
SELECT mission_id, unnest(string_to_array(variety_tags, '|'))
FROM staging_activity
WHERE variety_tags IS NOT NULL;
 
DROP TABLE staging_activity;
 
 
-- 4. ACTIVITY_LOCATION_CATEGORY
\copy activity_location_category (mission_id, category_name) FROM '/csvdata/Activity_LocationCategory.csv' WITH (FORMAT csv, HEADER true, NULL '')
 
-- 5. SPECIES_BADGE
\copy species_badge (
    vernacular_name, badge_type, requirement, badge_id, rule_type, rule_field,
    rule_operator, rule_value, description, image_earned, image_locked
) FROM '/csvdata/species_badge_db.csv' WITH (FORMAT csv, HEADER true, NULL '')

COMMIT;